### ISSUE TITLE
Compatibility issues

### ISSUE THREAD

**Issue by abutizi** [rodgc/ngx-socket-io#163]
Thank you for your hard work. I would appreciate some guidance here.

I have installed ngx-socket-io V4.5.1 on my angular app.

and on my Flask server I have the following versions:
pip install Python-SocketIO==4.5.1
pip install Flask-SocketIO==4.3.2

But it seems like I have dependency issues because I am getting this error:
TypeError: send() got an unexpected keyword argument 'binary'

I have no idea which versions to install the could work with ngx-socket-io V4.5.1 (latest version)?

**Comment by Helveg** [comment]
I think this is a Python error you posted? Correct? I don't think TypeScript has the notion of `keyword argument`? If this is a Python error, then it does not have to do with `ngx-socket-io` but is an error somewhere with your Python application. Feel free to reopen if this occurs somewhere on your JavaScript stack.

**Comment by abutizi** [comment]
Correct and the error means that the versions I’ve installed are incompatible. I’ve tried to install so many versions, yet I couldn’t make it compatible. What version of flask-socketio and python-socketio are compatible with ngx latest socketio package? 

Or opposite, what ngx socketio version are compatible with flask and python-socketio?

**Comment by Helveg** [comment]
Python code calling itself with incorrect arguments seems unlikely to be caused by the clientside SocketIO, and would still be an issue with your Python side libraries, and not this library.

I wish I could be of more help, but the best advice I can give is to post the error with the library this error occurs in, and if you're really convinced it's a client side issue, you can try to install all the different versions of `ngx-socket-io` as seen in this table https://www.npmjs.com/package/ngx-socket-io#install
