### ISSUE TITLE
angular 7 issue

### ISSUE THREAD

**Issue by Art2058** [rodgc/ngx-socket-io#15]
Cannot redeclare block-scoped variable 'ngDevMode'.

update please??

**Comment by jameihalt** [comment]
Can reproduce it after updating angular to 7.0

`ERROR in node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
node_modules/ngx-socket-io/node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
`

**Comment by moxival** [comment]
You should remove the `@angular/core` from your dependencies
```json
"dependencies": {
    "@angular/core": "^6.0.4",
    "core-js": "^2.4.1",
    "reflect-metadata": "^0.1.10",
    "rxjs": "^6.1.0",
    "socket.io": "^2.0.1",
    "socket.io-client": "^2.0.1",
    "zone.js": "^0.8.11"
  },
```

This creates new node_modules folder withing the ngx-socket-io which should not happen

**Comment by rodgc** [comment]
This issue was solved in version 2.0.0 thx to @bostondevin for the PR

**Comment by Art2058** [comment]
thank you!!

**Comment by minirobotdan** [comment]
Thanks!
